import type { Metadata } from 'next';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app',
};

export default function LoginLayout({ children }: { children: ReactNode }) {
  return <section>{children}</section>;
}
