export * from './user.repository';
export * from './training-record.repository';
export * from './favorite-training-record.repository';
export * from './notification.repository';
export * from './read-notification.repository';
export * from './advice-request.repository';
export * from './comment.repository';
export * from './point-history.repository';
export * from './thumbnail.repository';
