import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Reset Password',
  description: 'Generated by create next app',
};

export default function ResetPassLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section>{children}</section>;
}
