name: Deploy to Firebase

on:
  push:
    branches:
      - develop

jobs:
  main:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jsryudev/deploy-firebase-functions@v20.0.0
      env:
        FIREBASE_TOKEN: ${{ secrets.DEV_FIREBASE_TOKEN }}
        FIREBASE_PROJECT: ken-app-5926d
