name: Deploy to Firebase

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install firebase
        run: |
          npm install -g firebase-tools
      - name: make GOOGLE_APPLICATION_CREDENTIALS
        run: echo $GCLOUD_SERVICE_KEY | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
      - name: change environments
        run: |
          firebase use dev
      - name: change directory
        run: |
          cd functions
          npm install
          npm run build
          cd ..

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project dev
        env:
          GCP_SA_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
